version: "2"
services:
  app:
    command: "yarn start"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "4000:3000"
    restart: always
    container_name: gifm
