
// Principles
const principle1 = {
  number: '1',
  title: 'System-scale perspective',
  text: [
    'Addressing nature-based solutions for climate change adaptation and disaster risk reduction should start with a system-wide analysis of the local socio-economic, environmental, and institutional conditions.',
    'Spatial scale',
    `The physical landscape of coastal systems, rivers and deltas has been shaped by the interaction between sediments, hydrodynamics, and ecology. Often these systems are strongly influenced by both riverine and coastal processes, but also human use and existing infrastructure play a role. System integrity is influenced by fluxes of sediment, nutrients, and fresh and salt water occurring at different scales. Any change in these fluxes will trigger other processes that induce changes in
     landscape morphology and ecology. A change in fluxes could result in the reduction of sediment input or the alteration of currents. For example, alteration of upstream sediment loads may influence downstream coastline stability and in this way determine the success and feasibility of downstream or coastal interventions. The planning of nature-based measures should take into account these processes at various spatial scales, starting with the largest scale at which they play a role or can be influenced. Ideally, planning of a conventional engineering structure would take the same approach. However, whereas these large-scale considerations optimize functionality and avoid unforeseen effects for engineering structures, they are indispensable for the success of nature-based solutions.`,
    'Ecosystems are highly dependent on the larger enabling environmental processes. Often, ecosystems cannot be sustained by managing individual sites in isolation. The integrity and health of ecosystems at landscape scales determine the potential of nature-based solutions to limit flood risk. If evaluated on small spatial scales, the impact of nature-based solutions on risk reduction may seem trivial, whereas on larger scales the presence and integrity of ecosystems may make an enormous difference on the overall impact of flood events.',
    'Therefore, to appreciate and fully develop the potential of nature-based solutions for flood risk reduction, these solutions should be considered from the outset in terms of their potential over large spatial scales.',
    'Time scale',
    `In addition to considering appropriate spatial scales, a long time frame should be adopted to exploit the full potential of nature-based solutions. Ideally, time frames of 20 to 50 years or longer should be applied. For shoreline communities affected by flooding, the threat is increasing due to changes in watershed land use, more intense precipitation, sea-level rise, siltation of river mouths, increased storminess, and possible failure of conventional risk reduction structures (when
     present). Risk reduction strategies also need to reflect the range of conditions that can occur and how systems change over time. Consideration of the scale of the problem and how it will change over time is essential. Ecosystems evolve over decades or even centuries, which means that the benefits they provide also change over time. One of these benefits is that they can adapt to changing environmental and risk conditions, thereby potentially exceeding the design lifetime of engineered structures. Awareness-raising amongst coastal residents and other stakeholders that their system is changing, sea level is rising, and that each storm is different in terms of track, size, and intensity is crucial.`,
    'Local socio-economic and institutional context',
    `In addition to an evaluation of effects and feasibility on the environmental system, each infrastructure solution should be rooted in the local socio-economic and institutional context. Because nature-based solutions for flood risk are less common than traditional measures, their implementation in the local socio-economic and institutional context can be a challenge. For example, there is relatively little documentation of their effectiveness, costs, and benefits. Therefore, nature-based
    solutions may require a more integral perspective to ensure a common understanding of their role, including the integration of opinions and objectives of stakeholders. A larger array of stakeholders needs to be involved consistently in order to increase the legitimacy of the measures. Achieving broad acceptance for a nature-based solution may be complex and time consuming. This will pay off in later project stages. Ideally, such broad acceptance should also be obtained for conventional engineering projects.`
  ]
};

const principle2 = {
  number: '2',
  title: 'Risk and benefit assessment of full range of solutions',
  text: [
    'A thorough assessment of risks and benefits of the full range of possible measures should be conducted, covering risk reduction benefits as well as social and environmental effects.',
    'Flood risk management projects generally start with the identification of the three elements of risk: hazard, exposure, and vulnerability,. Conducting a risk assessment has two purposes. Firstly, the assessment provides a baseline understanding of what is at stake. It enables the decision-maker to define a risk reduction target which results in an acceptable level of residual risk. Secondly, the assessment is an important basis for analyzing the effectiveness of the various measures available for risk reduction.',
    'Risk assessments are not always conducted in nature-based projects despite their importance for successfully implementing a flood risk reduction measure. Lack of an appropriate risk assessment may result in a lack of understanding of the project’s risk reduction capabilities. Additionally, the broad portfolio of measures that could be used for flood risk reduction is not always taken into account. This may lead to implementation of suboptimal solutions in critical locations or to ill-fitted risk management strategies with potential long-term negative impacts for risk, ecosystems or other community interests.',
    'Although traditional risk assessment methods can be applied to nature-based solutions, they do not incorporate the full range of benefits generated by nature-based projects. To fully appreciate the potential of nature-based measures, risk assessments should be extended with a benefit assessment to quantify their ecosystem and socio-economic benefits. These additional benefits also need to be a standard element of cost-benefit analyses. This will enable a more holistic comparison to traditional engineering approaches that incorporates a project’s long term sustainability. Finally, risk assessments should incorporate projections of future changes in risk as a consequence of climatic, socio-economic, and institutional changes. Assessments should account for the dynamic nature of the risk reduction functions of natural ecosystems including the evolution of ecosystem services over time.'
  ]
};

const principle3 = {
  number: '3',
  title: 'Standardized performance evaluation',
  text: [
    'Nature-based solutions for flood risk management need to be tested, designed, and evaluated using quantitative criteria.',
    'There are international standards and guidelines for engineered flood management structures, such as the International Levee Handbook and the Coastal Engineering Manual. These standards and guidelines are adopted for design, testing, and construction. They not only provide guidance for implementation but also for evaluating the effectiveness of such measures. Similar standards for nature-based structures are not yet available. Consequently, the uptake of nature-based solutions would be facilitated by an open and transparent process to determine performance standards. This will allow for standardized quantification of their effectiveness in reducing hazard or exposure. A transparent process ensures that uncertainties are considered as part of the design. Further, such standards will enable comparison with conventional engineering interventions.',
    'Numerous documents are currently available that can inform designers. For example, for wave attenuation by vegetation there are numerous peer-reviewed papers documenting the latest advances in numerical models,. These numerical models can be used to make integrated designs as long as conservative estimates for vegetation parameters are adopted in order to avoid overestimating the performance of such measures. At the same time, there are several knowledge gaps regarding the performance of nature-based interventions for flood risk management. These gaps are mostly related to their performance under extreme storm conditions or tsunamis. Although numerical models are used to investigate performance of vegetated ecosystems under storm conditions, validation data from experiments or from the field is often lacking.',
    'Knowledge gaps also exist related to their persistence over longer time scales and subject to multiple events. Systematic knowledge development to fill these gaps is necessary to advance uptake of nature-based solutions. Developing and applying quantifiable engineering protocols for ecosystems will require close collaboration between ecologists, and engineers. This will increase our understanding of the role that ecosystems can play in risk reduction. Ultimately, it allows for impartial comparison of effectiveness, costs, and benefits of different types of solutions.'
  ]
};

const principle4 = {
  number: '4',
  title: 'Considering risk at the right scale',
  text: [
    'To use the full potential of nature-based solutions, a long time frame and landscape perspective should be adopted in making the case for solutions, as well as in the design.',
    `For shoreline communities affected by flooding the threat is increasing due to changes in watershed land cover, land-use regimes, more intense precipitation, sea-level rise and increased storminess.
    Hard structures put in place to reduce flood risk are often not maintained or upgraded and therefore no longer effective in many areas. Reducing risk needs to consider the system being protected, the range of conditions that can occur and how systems change over time. For example, many coastal Louisiana residents say they have never flooded from storms before, not realizing their coast is changing, sea level is rising, and that each storm is different in track, size and intensity. Considering the scale of the problem and how it will change over time is essential. If evaluated on small spatial scales, such as a single wetland in front of a levee, at a single moment in time, the impact of nature-based solutions on risk reduction may seem minor. However, ecosystems build up over decades or even centuries and may thereby exceed the design lifetime of engineered structures. Ecosystems are also highly dependent on the larger enabling environment, and cannot often be sustained by managing individual sites in isolation. The integrity and health of larger ecosystems at landscape or delta scales therefore determines the potential of nature-based solutions to help limit flood risk. Consequently, to appreciate and fully develop the potential of nature-based solutions for flood risk reduction, these solutions should be evaluated and assessed on their potential over large spatial and temporal scales. This automatically implies that construction and maintenance of ecosystems at these scales must often happen in a ‘hybrid’ manner, meaning that they go beyond traditional restoration alone and could make use of more engineered methods and interventions, such as river diversions and sediment nourishments for longer term maintenance. This requires large-scale system knowledge, modelling and adequate design prior to project implementation.`
  ]
};

const principle5 = {
  number: '5',
  title: 'Adaptive management',
  text: [
    'Nature-based solutions for flood risk management need adaptive management to ensure their sustainable performance.',
    `Just like engineering measures for flood risk management, nature-based solutions require maintenance after initial development to secure their long-term risk reduction potential.
    The dynamic nature of ecosystems combined with long-term trends and extensive risks, such as sea level rise and coastal development, asks for adaptive management of ecosystem-based strategies. The adaptive management cycle is built on a predictive outcome or target and consists of implementation, monitoring, data evaluation, and then adjustment of possible management measures. This cycle must be repeated with a fixed time interval for the full performance period of the measure. Adaptive management activities should be defined in a specific plan with funding available over time. These should include multiple management options in case of lack of expected performance of the implemented measure. For flood risk reduction this must include modeling as well as monitoring as the system should meet the criteria for risk reduction whenever the risk occurs. The adaptive management cycle should ensure consistent maintenance and development after project implementation and consolidate knowledge on effective measures and management methods.`
  ]
};


export { principle1, principle2, principle3, principle4, principle5 };
