
// Principles
const principle1 = {
  number: '1',
  title: 'System-scale perspective',
  text: [
    'Addressing nature-based solutions for climate change adaptation and disaster risk reduction should start with a system-wide analysis of the local socio-economic, environmental, and institutional conditions.',
    'Spatial scale',
    `The physical landscape of coastal systems, rivers and deltas has been shaped by the interaction between sediments, hydrodynamics, and ecology. Often these systems are strongly influenced by both riverine and coastal processes, but also human use and existing infrastructure play a role. System integrity is influenced by fluxes of sediment, nutrients, and fresh and salt water occurring at different scales. Any change in these fluxes will trigger other processes that induce changes in
     landscape morphology and ecology. A change in fluxes could result in the reduction of sediment input or the alteration of currents. For example, alteration of upstream sediment loads may influence downstream coastline stability and in this way determine the success and feasibility of downstream or coastal interventions. The planning of nature-based measures should take into account these processes at various spatial scales, starting with the largest scale at which they play a role or can be influenced. Ideally, planning of a conventional engineering structure would take the same approach. However, whereas these large-scale considerations optimize functionality and avoid unforeseen effects for engineering structures, they are indispensable for the success of nature-based solutions.`,
    'Ecosystems are highly dependent on the larger enabling environmental processes. Often, ecosystems cannot be sustained by managing individual sites in isolation. The integrity and health of ecosystems at landscape scales determine the potential of nature-based solutions to limit flood risk. If evaluated on small spatial scales, the impact of nature-based solutions on risk reduction may seem trivial, whereas on larger scales the presence and integrity of ecosystems may make an enormous difference on the overall impact of flood events.',
    'Therefore, to appreciate and fully develop the potential of nature-based solutions for flood risk reduction, these solutions should be considered from the outset in terms of their potential over large spatial scales.',
    'Time scale',
    `In addition to considering appropriate spatial scales, a long time frame should be adopted to exploit the full potential of nature-based solutions. Ideally, time frames of 20 to 50 years or longer should be applied. For shoreline communities affected by flooding, the threat is increasing due to changes in watershed land use, more intense precipitation, sea-level rise, siltation of river mouths, increased storminess, and possible failure of conventional risk reduction structures (when
     present). Risk reduction strategies also need to reflect the range of conditions that can occur and how systems change over time. Consideration of the scale of the problem and how it will change over time is essential. Ecosystems evolve over decades or even centuries, which means that the benefits they provide also change over time. One of these benefits is that they can adapt to changing environmental and risk conditions, thereby potentially exceeding the design lifetime of engineered structures. Awareness-raising amongst coastal residents and other stakeholders that their system is changing, sea level is rising, and that each storm is different in terms of track, size, and intensity is crucial.`,
    'Local socio-economic and institutional context',
    `In addition to an evaluation of effects and feasibility on the environmental system, each infrastructure solution should be rooted in the local socio-economic and institutional context. Because nature-based solutions for flood risk are less common than traditional measures, their implementation in the local socio-economic and institutional context can be a challenge. For example, there is relatively little documentation of their effectiveness, costs, and benefits. Therefore, nature-based
    solutions may require a more integral perspective to ensure a common understanding of their role, including the integration of opinions and objectives of stakeholders. A larger array of stakeholders needs to be involved consistently in order to increase the legitimacy of the measures. Achieving broad acceptance for a nature-based solution may be complex and time consuming. This will pay off in later project stages. Ideally, such broad acceptance should also be obtained for conventional engineering projects.`
  ]
};

const principle2 = {
  number: '2',
  title: 'Standardized performance evaluation',
  text: [
    'Nature-based solutions for flood risk management need to be tested, designed, and evaluated, using the same criteria as hard engineering structures.',
    `For design and functioning of hard engineering structures, criteria are determined and consolidated in manuals and guidelines.
    To determine effectiveness of nature-based interventions that aim to reduce hazard or exposure or are chosen as an alternative to structural measures, and to enable comparison with hard or gray engineered interventions, nature-based solutions must be held to measurable standards. There are several knowledge gaps regarding the performance of nature-based interventions for flood risk management. These gaps are mostly related to their performance under extreme conditions (e.g. with storms or tsunamis) and their persistence on longer time-scales under multiple events. For engineered structures there are international standards, such as the levee manual[1] and the Coastal Engineering Manual[2], that are followed for design, testing, and construction. These manuals provide guidance for implementation but also for testing of effectiveness. Similar standards for nature-based structures are not yet available, but standardized design criteria will rapidly advance as current knowledge gaps are filled. In addition, generic functional parameters for different habitat types can potentially be developed and captured in manuals (e.g. minimum and maximum dissipation coefficients for habitat types or species). In addition, developing and applying measurable engineering protocols to ecosystems will require close collaboration between ecologists and engineers. Doing this will increase our understanding of the role that ecosystems can play in risk reduction and ultimately allow for impartial comparison of effectiveness, costs, and benefits of different types of solutions.`
  ]
};

const principle3 = {
  number: '3',
  title: 'Integration with ecosystem conservation and restoration',
  text: [
    'Nature-based solutions for flood risk management should make use of existing ecosystems and native species, and comply with basic principles of ecological restoration and conservation.',
    `Restoration, conservation, and management of ecosystems will constitute a crucial element of implementation of nature-based solutions for flood risk management.
    Ecological conservation and restoration is a scientific discipline with a large body of theory and practice. However, this knowledge is not always integrated in on-the-ground-project implementation. For example, large-scale mangrove planting efforts are often executed with unsuitable species in unsuitable areas and therefore fail unnecessarily. Moreover, poorly planned restoration and planting efforts may result in unanticipated effects on other valuable ecosystems, such as intertidal flats and seagrass beds. Restoration practices, similar to risk assessments, should start with a system evaluation to determine the type of ecosystem that used to exist and to identify limiting factors for the restoration of existing ecosystem elements or the construction of new ones.  On-the-ground project efforts can then mostly focus on mitigating those limiting factors or working within or expected constraints. Once abiotic conditions for ecosystem recovery are restored, planting is mostly not needed. Making use of available knowledge on ecosystem restoration and management will not only reduce the risk of failure in project implementation, but also avoid undesirable replacement or destruction of other valuable ecosystems for a nature-based flood risk reduction project. For example, in many countries mangroves are considered crucial for reduction of waves that are generated by coastal storms. However, often mangrove habitat, the upper intertidal area, is already used for fish and shrimp farming, agriculture, or for living. Therefore, mangrove restoration is often executed in the lower intertidal, negatively impacting shellfish, birds, seagrasses, and dugongs that live there. Such tradeoffs need to be anticipated so that communities are aware of both risk reduction outcomes and food security and ecological implications.`
  ]
};

const principle4 = {
  number: '4',
  title: 'Considering risk at the right scale',
  text: [
    'To use the full potential of nature-based solutions, a long time frame and landscape perspective should be adopted in making the case for solutions, as well as in the design.',
    `For shoreline communities affected by flooding the threat is increasing due to changes in watershed land cover, land-use regimes, more intense precipitation, sea-level rise and increased storminess.
    Hard structures put in place to reduce flood risk are often not maintained or upgraded and therefore no longer effective in many areas. Reducing risk needs to consider the system being protected, the range of conditions that can occur and how systems change over time. For example, many coastal Louisiana residents say they have never flooded from storms before, not realizing their coast is changing, sea level is rising, and that each storm is different in track, size and intensity. Considering the scale of the problem and how it will change over time is essential. If evaluated on small spatial scales, such as a single wetland in front of a levee, at a single moment in time, the impact of nature-based solutions on risk reduction may seem minor. However, ecosystems build up over decades or even centuries and may thereby exceed the design lifetime of engineered structures. Ecosystems are also highly dependent on the larger enabling environment, and cannot often be sustained by managing individual sites in isolation. The integrity and health of larger ecosystems at landscape or delta scales therefore determines the potential of nature-based solutions to help limit flood risk. Consequently, to appreciate and fully develop the potential of nature-based solutions for flood risk reduction, these solutions should be evaluated and assessed on their potential over large spatial and temporal scales. This automatically implies that construction and maintenance of ecosystems at these scales must often happen in a ‘hybrid’ manner, meaning that they go beyond traditional restoration alone and could make use of more engineered methods and interventions, such as river diversions and sediment nourishments for longer term maintenance. This requires large-scale system knowledge, modelling and adequate design prior to project implementation.`
  ]
};

const principle5 = {
  number: '5',
  title: 'Adaptive management',
  text: [
    'Nature-based solutions for flood risk management need adaptive management to ensure their sustainable performance.',
    `Just like engineering measures for flood risk management, nature-based solutions require maintenance after initial development to secure their long-term risk reduction potential.
    The dynamic nature of ecosystems combined with long-term trends and extensive risks, such as sea level rise and coastal development, asks for adaptive management of ecosystem-based strategies. The adaptive management cycle is built on a predictive outcome or target and consists of implementation, monitoring, data evaluation, and then adjustment of possible management measures. This cycle must be repeated with a fixed time interval for the full performance period of the measure. Adaptive management activities should be defined in a specific plan with funding available over time. These should include multiple management options in case of lack of expected performance of the implemented measure. For flood risk reduction this must include modeling as well as monitoring as the system should meet the criteria for risk reduction whenever the risk occurs. The adaptive management cycle should ensure consistent maintenance and development after project implementation and consolidate knowledge on effective measures and management methods.`
  ]
};


export { principle1, principle2, principle3, principle4, principle5 };
