
// Principles
const principle1 = {
  number: '1',
  title: 'System-scale perspective',
  text: [
    '<p>Addressing nature-based solutions for climate change adaptation and disaster risk reduction should start with a system-wide analysis of the local socio-economic, environmental, and institutional conditions.</p>',
    '<h3>Spatial scale</h3>',
    `<p>The physical landscape of coastal systems, rivers and deltas has been shaped by the interaction between sediments, hydrodynamics, and ecology. Often these systems are strongly influenced by both riverine and coastal processes, but also human use and existing infrastructure play a role. System integrity is influenced by fluxes of sediment, nutrients, and fresh and salt water occurring at different scales. Any change in these fluxes will trigger other processes that induce changes in
     landscape morphology and ecology. A change in fluxes could result in the reduction of sediment input or the alteration of currents. For example, alteration of upstream sediment loads may influence downstream coastline stability and in this way determine the success and feasibility of downstream or coastal interventions. The planning of nature-based measures should take into account these processes at various spatial scales, starting with the largest scale at which they play a role or can be influenced. Ideally, planning of a conventional engineering structure would take the same approach. However, whereas these large-scale considerations optimize functionality and avoid unforeseen effects for engineering structures, they are indispensable for the success of nature-based solutions.</p>`,
    '<p>Ecosystems are highly dependent on the larger enabling environmental processes. Often, ecosystems cannot be sustained by managing individual sites in isolation. The integrity and health of ecosystems at landscape scales determine the potential of nature-based solutions to limit flood risk. If evaluated on small spatial scales, the impact of nature-based solutions on risk reduction may seem trivial, whereas on larger scales the presence and integrity of ecosystems may make an enormous difference on the overall impact of flood events.</p>',
    '<p>Therefore, to appreciate and fully develop the potential of nature-based solutions for flood risk reduction, these solutions should be considered from the outset in terms of their potential over large spatial scales.</p>',
    '<h3>Time scale</h3>',
    `<p>In addition to considering appropriate spatial scales, a long time frame should be adopted to exploit the full potential of nature-based solutions. Ideally, time frames of 20 to 50 years or longer should be applied. For shoreline communities affected by flooding, the threat is increasing due to changes in watershed land use, more intense precipitation, sea-level rise, siltation of river mouths, increased storminess, and possible failure of conventional risk reduction structures (when
     present). Risk reduction strategies also need to reflect the range of conditions that can occur and how systems change over time. Consideration of the scale of the problem and how it will change over time is essential. Ecosystems evolve over decades or even centuries, which means that the benefits they provide also change over time. One of these benefits is that they can adapt to changing environmental and risk conditions, thereby potentially exceeding the design lifetime of engineered structures. Awareness-raising amongst coastal residents and other stakeholders that their system is changing, sea level is rising, and that each storm is different in terms of track, size, and intensity is crucial.</p>`,
    '<h3>Local socio-economic and institutional context</h3>',
    `<p>In addition to an evaluation of effects and feasibility on the environmental system, each infrastructure solution should be rooted in the local socio-economic and institutional context. Because nature-based solutions for flood risk are less common than traditional measures, their implementation in the local socio-economic and institutional context can be a challenge. For example, there is relatively little documentation of their effectiveness, costs, and benefits. Therefore, nature-based
    solutions may require a more integral perspective to ensure a common understanding of their role, including the integration of opinions and objectives of stakeholders. A larger array of stakeholders needs to be involved consistently in order to increase the legitimacy of the measures. Achieving broad acceptance for a nature-based solution may be complex and time consuming. This will pay off in later project stages. Ideally, such broad acceptance should also be obtained for conventional engineering projects.</p>`
  ]
};

const principle2 = {
  number: '2',
  title: 'Risk and benefit assessment of full range of solutions',
  text: [
    '<p>A thorough assessment of risks and benefits of the full range of possible measures should be conducted, covering risk reduction benefits as well as social and environmental effects.</p>',
    '<p>Flood risk management projects generally start with the identification of the three elements of risk: hazard, exposure, and vulnerability,. Conducting a risk assessment has two purposes. Firstly, the assessment provides a baseline understanding of what is at stake. It enables the decision-maker to define a risk reduction target which results in an acceptable level of residual risk. Secondly, the assessment is an important basis for analyzing the effectiveness of the various measures available for risk reduction.</p>',
    '<p>Risk assessments are not always conducted in nature-based projects despite their importance for successfully implementing a flood risk reduction measure. Lack of an appropriate risk assessment may result in a lack of understanding of the project’s risk reduction capabilities. Additionally, the broad portfolio of measures that could be used for flood risk reduction is not always taken into account. This may lead to implementation of suboptimal solutions in critical locations or to ill-fitted risk management strategies with potential long-term negative impacts for risk, ecosystems or other community interests.</p>',
    '<p>Although traditional risk assessment methods can be applied to nature-based solutions, they do not incorporate the full range of benefits generated by nature-based projects. To fully appreciate the potential of nature-based measures, risk assessments should be extended with a benefit assessment to quantify their ecosystem and socio-economic benefits. These additional benefits also need to be a standard element of cost-benefit analyses. This will enable a more holistic comparison to traditional engineering approaches that incorporates a project’s long term sustainability. Finally, risk assessments should incorporate projections of future changes in risk as a consequence of climatic, socio-economic, and institutional changes. Assessments should account for the dynamic nature of the risk reduction functions of natural ecosystems including the evolution of ecosystem services over time.</p>'
  ]
};

const principle3 = {
  number: '3',
  title: 'Standardized performance evaluation',
  text: [
    '<p>Nature-based solutions for flood risk management need to be tested, designed, and evaluated using quantitative criteria.</p>',
    '<p>There are international standards and guidelines for engineered flood management structures, such as the International Levee Handbook and the Coastal Engineering Manual. These standards and guidelines are adopted for design, testing, and construction. They not only provide guidance for implementation but also for evaluating the effectiveness of such measures. Similar standards for nature-based structures are not yet available. Consequently, the uptake of nature-based solutions would be facilitated by an open and transparent process to determine performance standards. This will allow for standardized quantification of their effectiveness in reducing hazard or exposure. A transparent process ensures that uncertainties are considered as part of the design. Further, such standards will enable comparison with conventional engineering interventions.</p>',
    '<p>Numerous documents are currently available that can inform designers. For example, for wave attenuation by vegetation there are numerous peer-reviewed papers documenting the latest advances in numerical models,. These numerical models can be used to make integrated designs as long as conservative estimates for vegetation parameters are adopted in order to avoid overestimating the performance of such measures. At the same time, there are several knowledge gaps regarding the performance of nature-based interventions for flood risk management. These gaps are mostly related to their performance under extreme storm conditions or tsunamis. Although numerical models are used to investigate performance of vegetated ecosystems under storm conditions, validation data from experiments or from the field is often lacking.</p>',
    '<p>Knowledge gaps also exist related to their persistence over longer time scales and subject to multiple events. Systematic knowledge development to fill these gaps is necessary to advance uptake of nature-based solutions. Developing and applying quantifiable engineering protocols for ecosystems will require close collaboration between ecologists, and engineers. This will increase our understanding of the role that ecosystems can play in risk reduction. Ultimately, it allows for impartial comparison of effectiveness, costs, and benefits of different types of solutions.</p>'
  ]
};

const principle4 = {
  number: '4',
  title: 'Integration with ecosystem conservation and restoration',
  text: [
    '<p>Nature-based solutions for flood risk management should make use of existing ecosystems, native species, and comply with basic principles of ecological restoration and conservation.</p>',
    `<p>Restoration, conservation, and management of ecosystems are crucial elements of the implementation of nature-based solutions for flood risk management. Ecological conservation and restoration and morphology are scientific disciplines with large bodies of theory and practice that will advance proper implementation of nature-based solutions. For example, it is known that ecosystems that are more diverse are also more productive and more resilient to disturbances. Further, there is ample
    evidence that restoration by planting of a single crop or exotic species leads to adverse effects and therefore restoration efforts better focus on reconstructing proper abiotic conditions. However, this knowledge is not always reflected in on-the-ground flood risk reduction projects. Large-scale mangrove planting efforts, for example, are often conducted with unsuitable species in unsuitable areas and therefore fail unnecessarily. Moreover, poorly planned restoration and planting efforts may result in unanticipated effects on other valuable ecosystems such as intertidal flats and sea grass beds. As for risk assessments, restoration practices should start with a system evaluation to determine the pre-existing types of ecosystems and abiotic processes. System evaluations help identify opportunities and constraints for effective conservation and restoration of ecosystems. Present and future conditions should be taken into account to determine the target ecosystem and the feasibility of restoring it. Sometimes conditions are altered to such an extent that returning to original states is not realistic. This may warrant restoration to another type of ecosystem and adjustment of restoration targets. In addition, climate change impacts on ecosystems may result in transitions between ecosystems. It is important to understand the risk reduction value of the current ecosystem and how that risk profile will change as the ecosystem changes.</p>`,
    `<p>Leveraging available knowledge on ecosystem restoration and management will not only reduce the risk of failure in project implementation, but also avoid undesirable side effects such as the replacement or destruction of other valuable ecosystems. For example, mangroves are often considered crucial for reduction of waves generated by coastal storms. However, previous mangrove habitats (the high intertidal zone) are often already used for aquaculture, agriculture, or habitation. As a
    consequence, mangrove restoration is often conducted in the lower intertidal zone. Restoration in this zone can negatively impact shellfish, birds, sea grasses, and dugongs. Such tradeoffs need to be anticipated so that communities are aware of risk reduction outcomes, including the implications for food security and ecosystems. The preferred option for mangrove restoration is restoring conditions that are favorable for natural establishment of mangroves. Guidelines for restoration of ecosystems can be found on the Ecoshape wiki pages. A good manual for informed mangrove restoration is also available.</p>`
  ]
};

const principle5 = {
  number: '5',
  title: 'Adaptive management',
  text: [
    '<p>Nature-based solutions for flood risk management need adaptive management based on long-term monitoring. This ensures their sustainable performance.</p>',
    '<p>As nature-based solutions evolve over time, they require continuous management and monitoring of their effectiveness. The management of nature-based solutions should strongly draw on knowledge of ecosystem management, which requires a proper understanding of ecosystem dynamics. One example of an adaptive management strategy is the nourishment of extra sediment, as sometimes practiced in beach and dune systems. Another example is the exclusion of grazers or predators if these limit ecosystem recovery. The dynamic nature of ecosystems combined with long-term trends necessitates adaptive management of any ecosystem-based strategy. Implementation of nature-based solutions should therefore be accompanied by an adaptive management plan.</p>',
    `<p>Adaptive management is a systematic approach that facilitates flexible decision-making. It is an iterative process in which management actions are followed by targeted monitoring and assessment. As outcomes from current and future management actions become better understood, the decision-making and management can be refined. The adaptive management cycle is built on a predictive outcome or target. It consists of implementation, monitoring, data evaluation, decision-making, and adjustment
    of possible management measures. This cycle should be repeated at a regular interval over the lifetime of the measure. Adaptive management activities should be defined in a specific plan, with funding made available over time. Such activities include multiple management scenarios should the measure not perform as expected. Assessment of the flood risk reduction potential may include modeling and monitoring, while the system should meet the criteria for risk reduction whenever a hazard occurs. The adaptive management cycle ensures consistent management after the project implementation, but also provides a basis to develop lessons learned for future project implementation. Similarly, the cycle should include documentation of effective measures and management methods. Flexibility in the donor requirements helps to enable adaptive management of nature-based solutions for flood risk management.</p>`
  ]
};


export { principle1, principle2, principle3, principle4, principle5 };
